/**
 * @license
 * Copyright 2025 ContextGo (contextgo.io)
 * SPDX-License-Identifier: Apache-2.0
 */

import type { ContextTriggerSpec } from './types';

export const CONTEXT_ENGINE_BUILTIN_TRIGGERS: readonly ContextTriggerSpec[] = [
  {
    id: 'hook.context-window-prepared',
    kind: 'hook',
    source: 'hook',
    builder: 'session_compaction',
    jobType: 'session_compaction',
    scopeKind: 'conversation',
    event: 'context.window.prepared',
    label: 'Context window prepared',
    defaultPriority: 'medium',
    defaultReason: 'Refresh the session working set after preparing a new context window.',
  },
  {
    id: 'hook.session-turn-completed',
    kind: 'hook',
    source: 'hook',
    builder: 'session_compaction',
    jobType: 'session_compaction',
    scopeKind: 'conversation',
    event: 'session.turn.completed',
    label: 'Session turn completed',
    defaultPriority: 'medium',
    defaultReason: 'Compact the latest session turn into reusable working context.',
  },
  {
    id: 'lifecycle.session-interrupted',
    kind: 'lifecycle',
    source: 'lifecycle',
    builder: 'session_compaction',
    jobType: 'session_compaction',
    scopeKind: 'conversation',
    event: 'session.interrupted',
    label: 'Session interrupted',
    defaultPriority: 'high',
    defaultReason: 'Capture interruption signals before the session context drifts.',
  },
  {
    id: 'derived.project-promotion',
    kind: 'derived',
    source: 'derived',
    builder: 'project_promotion',
    jobType: 'project_promotion',
    scopeKind: 'project',
    event: 'context.job.completed',
    label: 'Session compaction completed',
    defaultPriority: 'medium',
    defaultReason: 'Promote stable session takeaways into project knowledge.',
  },
  {
    id: 'manual.session-compaction',
    kind: 'manual',
    source: 'manual',
    builder: 'session_compaction',
    jobType: 'session_compaction',
    scopeKind: 'conversation',
    event: 'manual.session_compaction',
    label: 'Manual session compaction',
    defaultPriority: 'medium',
    defaultReason: 'Manually compact the current session into a reusable working set.',
  },
  {
    id: 'manual.project-promotion',
    kind: 'manual',
    source: 'manual',
    builder: 'project_promotion',
    jobType: 'project_promotion',
    scopeKind: 'project',
    event: 'manual.project_promotion',
    label: 'Manual project promotion',
    defaultPriority: 'medium',
    defaultReason: 'Manually promote stable project knowledge.',
  },
  {
    id: 'manual.session-pattern-detection',
    kind: 'manual',
    source: 'manual',
    builder: 'planned',
    jobType: 'session_pattern_detection',
    scopeKind: 'conversation',
    event: 'manual.session_pattern_detection',
    label: 'Manual session pattern detection',
    defaultPriority: 'medium',
    defaultReason: 'Manually inspect recurring patterns in the current session.',
  },
  {
    id: 'manual.space-memory-distillation',
    kind: 'manual',
    source: 'manual',
    builder: 'planned',
    jobType: 'space_memory_distillation',
    scopeKind: 'space',
    event: 'manual.space_memory_distillation',
    label: 'Manual space memory distillation',
    defaultPriority: 'medium',
    defaultReason: 'Manually distill shared space memory and profile signals from recent project activity.',
  },
  {
    id: 'manual.connector-digest',
    kind: 'manual',
    source: 'manual',
    builder: 'planned',
    jobType: 'connector_digest',
    scopeKind: 'space',
    event: 'manual.connector_digest',
    label: 'Manual connector digest',
    defaultPriority: 'medium',
    defaultReason: 'Manually digest external connector updates into context records.',
  },
  {
    id: 'manual.project-capability-curation',
    kind: 'manual',
    source: 'manual',
    builder: 'planned',
    jobType: 'project_capability_curation',
    scopeKind: 'project',
    event: 'manual.project_capability_curation',
    label: 'Manual project capability curation',
    defaultPriority: 'medium',
    defaultReason:
      'Manually refresh project docs, AGENTS append proposals, and skill proposals from local automation evidence.',
  },
  {
    id: 'timer.session-pattern-detection',
    kind: 'timer',
    source: 'timer',
    builder: 'planned',
    jobType: 'session_pattern_detection',
    scopeKind: 'conversation',
    event: 'timer.session_pattern_detection',
    label: 'Session pattern detection',
    defaultPriority: 'medium',
    defaultReason: 'Periodically inspect the session for recurring patterns.',
  },
  {
    id: 'timer.space-memory-distillation',
    kind: 'timer',
    source: 'timer',
    builder: 'planned',
    jobType: 'space_memory_distillation',
    scopeKind: 'space',
    event: 'timer.space_memory_distillation',
    label: 'Space memory distillation',
    defaultPriority: 'high',
    defaultReason: 'Periodically distill shared space memory and profile signals from recent project activity.',
  },
  {
    id: 'timer.connector-digest',
    kind: 'timer',
    source: 'timer',
    builder: 'planned',
    jobType: 'connector_digest',
    scopeKind: 'space',
    event: 'timer.connector_digest',
    label: 'Connector digest',
    defaultPriority: 'medium',
    defaultReason: 'Periodically digest connector updates into source-aware context.',
  },
  {
    id: 'timer.project-capability-curation',
    kind: 'timer',
    source: 'timer',
    builder: 'planned',
    jobType: 'project_capability_curation',
    scopeKind: 'project',
    event: 'timer.project_capability_curation',
    label: 'Project capability curation',
    defaultPriority: 'medium',
    defaultReason: 'Periodically refresh project docs and append-first proposals from local automation evidence.',
  },
  {
    id: 'connector.connector-digest',
    kind: 'connector',
    source: 'connector',
    builder: 'planned',
    jobType: 'connector_digest',
    scopeKind: 'space',
    event: 'connector.source.ingested',
    label: 'Connector source ingested',
    defaultPriority: 'medium',
    defaultReason: 'Digest newly ingested connector content into reusable context.',
  },
] as const;
