import type { ConnectorCategory, ConnectorDefinition, ConnectorSupportSource } from './types';
import { CONNECTOR_LOCAL_LOGOS } from './localLogos';

type RawConnectorDefinition = Omit<ConnectorDefinition, 'localLogo' | 'supportStatus'> & {
  localLogo?: string;
  supportStatus?: ConnectorDefinition['supportStatus'];
  externalCatalogConnector?: string;
};

const CONNECTOR_SUPPORT_SOURCES: Record<string, ConnectorSupportSource[]> = {
  'contextgo-clipboard': [
    {
      kind: 'official-runtime',
      label: 'cgo activity clipboard',
      url: 'https://github.com/contextgo/connector',
      description: 'Connector CLI activity runtime for clipboard observation, config, and collect workflows.',
    },
    {
      kind: 'connector-repo',
      label: 'Connector Repository',
      url: 'https://github.com/contextgo/connector',
      description: 'The standalone connector project owns the clipboard runtime, activity store, and collect pipeline.',
    },
  ],
  'contextgo-browser-extension': [
    {
      kind: 'official-runtime',
      label: 'cgo activity browser-extension',
      url: 'https://github.com/contextgo/connector',
      description: 'Connector CLI activity runtime for browser extension ingest, health checks, and collect workflows.',
    },
    {
      kind: 'connector-repo',
      label: 'Connector Repository',
      url: 'https://github.com/contextgo/connector',
      description:
        'The standalone connector project owns the browser extension runtime, packaging, ingest contract, and protocol evolution.',
    },
  ],
  lark: [
    {
      kind: 'official-docs',
      label: 'Feishu Open Platform',
      url: 'https://open.feishu.cn/document/home/index',
      description: 'Official developer documentation for Feishu/Lark app credentials, OAuth, and API scopes.',
    },
    {
      kind: 'official-runtime',
      label: 'lark-cli',
      url: 'https://github.com/larksuite/cli',
      description: 'Official CLI used for Feishu/Lark app configuration, authentication, and API command workflows.',
    },
    {
      kind: 'connector-repo',
      label: 'Connector Repository',
      url: 'https://github.com/contextgo/connector',
      description:
        'The standalone connector project owns the Feishu runtime wrapper, space-scoped runtime state, and official CLI passthrough contract.',
    },
  ],
  'google-drive': [
    {
      kind: 'official-docs',
      label: 'Google Workspace CLI Docs',
      url: 'https://developers.google.com/workspace',
      description: 'Official Google Workspace platform documentation for Drive and adjacent product surfaces.',
    },
    {
      kind: 'official-runtime',
      label: 'Connector CLI',
      url: 'https://github.com/contextgo/connector',
      description: 'Connector-project owned runtime boundary for future Google Drive native CLI and collect workflows.',
    },
    {
      kind: 'connector-repo',
      label: 'Connector Repository',
      url: 'https://github.com/contextgo/connector',
      description:
        'The standalone connector project owns the Google Drive runtime migration and native capability surface.',
    },
  ],
  'google-docs': [
    {
      kind: 'official-docs',
      label: 'Google Workspace CLI Docs',
      url: 'https://developers.google.com/workspace',
      description: 'Official Google Workspace platform documentation for Docs and adjacent product surfaces.',
    },
    {
      kind: 'official-runtime',
      label: 'Connector CLI',
      url: 'https://github.com/contextgo/connector',
      description: 'Connector-project owned runtime boundary for future Google Docs native CLI and collect workflows.',
    },
    {
      kind: 'connector-repo',
      label: 'Connector Repository',
      url: 'https://github.com/contextgo/connector',
      description:
        'The standalone connector project owns the Google Docs runtime migration and native capability surface.',
    },
  ],
  'google-sheets': [
    {
      kind: 'official-docs',
      label: 'Google Workspace CLI Docs',
      url: 'https://developers.google.com/workspace',
      description: 'Official Google Workspace platform documentation for Sheets and adjacent product surfaces.',
    },
    {
      kind: 'official-runtime',
      label: 'Connector CLI',
      url: 'https://github.com/contextgo/connector',
      description:
        'Connector-project owned runtime boundary for future Google Sheets native CLI and collect workflows.',
    },
    {
      kind: 'connector-repo',
      label: 'Connector Repository',
      url: 'https://github.com/contextgo/connector',
      description:
        'The standalone connector project owns the Google Sheets runtime migration and native capability surface.',
    },
  ],
  gmail: [
    {
      kind: 'official-docs',
      label: 'Google Workspace CLI Docs',
      url: 'https://developers.google.com/workspace',
      description: 'Official Google Workspace platform documentation for Gmail and adjacent product surfaces.',
    },
    {
      kind: 'official-runtime',
      label: 'Connector CLI',
      url: 'https://github.com/contextgo/connector',
      description: 'Connector-project owned runtime boundary for future Gmail native CLI and collect workflows.',
    },
    {
      kind: 'connector-repo',
      label: 'Connector Repository',
      url: 'https://github.com/contextgo/connector',
      description: 'The standalone connector project owns the Gmail runtime migration and native capability surface.',
    },
  ],
  'google-calendar': [
    {
      kind: 'official-docs',
      label: 'Google Workspace CLI Docs',
      url: 'https://developers.google.com/workspace',
      description: 'Official Google Workspace platform documentation for Calendar and adjacent product surfaces.',
    },
    {
      kind: 'official-runtime',
      label: 'Connector CLI',
      url: 'https://github.com/contextgo/connector',
      description:
        'Connector-project owned runtime boundary for future Google Calendar native CLI and collect workflows.',
    },
    {
      kind: 'connector-repo',
      label: 'Connector Repository',
      url: 'https://github.com/contextgo/connector',
      description:
        'The standalone connector project owns the Google Calendar runtime migration and native capability surface.',
    },
  ],
};

export const CONNECTOR_CATEGORY_ORDER: ConnectorCategory[] = [
  'contextgo',
  'googleWorkspace',
  'collaboration',
  'development',
  'knowledge',
  'design',
  'storage',
  'business',
  'data',
];

const RAW_CONNECTORS: RawConnectorDefinition[] = [
  {
    id: 'contextgo-clipboard',
    name: 'ContextGo Clipboard',
    websiteUrl: 'https://contextgo.io',
    domain: 'contextgo.io',
    category: 'contextgo',
    resources: ['clipboard'],
    authType: 'native',
    stage: 'priority',
    summary:
      'Clipboard runtime now lives in the standalone connector project, which owns observation, retention, and collect workflows.',
    implementationOwner: 'connector-repo',
    externalCatalogConnector: 'clipboard',
    supportSources: CONNECTOR_SUPPORT_SOURCES['contextgo-clipboard'],
  },
  {
    id: 'contextgo-browser-extension',
    name: 'ContextGo Browser Extension',
    websiteUrl: 'https://contextgo.io',
    domain: 'contextgo.io',
    category: 'contextgo',
    resources: ['browserHistory', 'webPages'],
    authType: 'extension',
    stage: 'priority',
    summary:
      'The browser extension runtime lives in the standalone connector project, and ContextGo only consumes its host-side outputs after ingestion.',
    implementationOwner: 'connector-repo',
    externalCatalogConnector: 'browser-extension',
    supportSources: CONNECTOR_SUPPORT_SOURCES['contextgo-browser-extension'],
  },
  {
    id: 'chrome-history',
    name: 'Chrome History',
    websiteUrl: 'https://www.google.com/chrome/',
    domain: 'google.com',
    category: 'contextgo',
    resources: ['browserHistory', 'webPages'],
    authType: 'native',
    stage: 'planned',
  },
  {
    id: 'file-format',
    name: 'File Format',
    websiteUrl: 'https://contextgo.io',
    domain: 'contextgo.io',
    category: 'contextgo',
    resources: ['files', 'docs'],
    authType: 'native',
    stage: 'planned',
  },
  {
    id: 'search',
    name: 'Search',
    websiteUrl: 'https://contextgo.io',
    domain: 'contextgo.io',
    category: 'contextgo',
    resources: ['webPages', 'analytics'],
    authType: 'none',
    stage: 'planned',
  },
  {
    id: 'google-drive',
    name: 'Google Drive',
    websiteUrl: 'https://drive.google.com',
    domain: 'drive.google.com',
    category: 'googleWorkspace',
    resources: ['files', 'docs', 'sheets'],
    authType: 'oauth',
    stage: 'priority',
    summary:
      'Google Drive should now be modeled as a connector-project owned native boundary, not as a ContextGo inline sidecar.',
    implementationOwner: 'connector-repo',
    externalCatalogConnector: 'google-drive',
    supportSources: CONNECTOR_SUPPORT_SOURCES['google-drive'],
  },
  {
    id: 'google-docs',
    name: 'Google Docs',
    websiteUrl: 'https://docs.google.com',
    domain: 'docs.google.com',
    category: 'googleWorkspace',
    resources: ['docs'],
    authType: 'oauth',
    stage: 'priority',
    summary:
      'Google Docs should now be modeled as a connector-project owned native boundary, not as a ContextGo inline sidecar.',
    implementationOwner: 'connector-repo',
    externalCatalogConnector: 'google-docs',
    supportSources: CONNECTOR_SUPPORT_SOURCES['google-docs'],
  },
  {
    id: 'google-sheets',
    name: 'Google Sheets',
    websiteUrl: 'https://sheets.google.com',
    domain: 'sheets.google.com',
    category: 'googleWorkspace',
    resources: ['sheets', 'docs'],
    authType: 'oauth',
    stage: 'priority',
    summary:
      'Google Sheets should now be modeled as a connector-project owned native boundary, not as a ContextGo inline sidecar.',
    implementationOwner: 'connector-repo',
    externalCatalogConnector: 'google-sheets',
    supportSources: CONNECTOR_SUPPORT_SOURCES['google-sheets'],
  },
  {
    id: 'google-calendar',
    name: 'Google Calendar',
    websiteUrl: 'https://calendar.google.com',
    domain: 'calendar.google.com',
    category: 'googleWorkspace',
    resources: ['calendar'],
    authType: 'oauth',
    stage: 'priority',
    summary:
      'Google Calendar should now be modeled as a connector-project owned native boundary, not as a ContextGo inline sidecar.',
    implementationOwner: 'connector-repo',
    externalCatalogConnector: 'google-calendar',
    supportSources: CONNECTOR_SUPPORT_SOURCES['google-calendar'],
  },
  {
    id: 'gmail',
    name: 'Gmail',
    websiteUrl: 'https://mail.google.com',
    domain: 'mail.google.com',
    category: 'googleWorkspace',
    resources: ['email'],
    authType: 'oauth',
    stage: 'priority',
    summary:
      'Gmail should now be modeled as a connector-project owned native boundary, not as a ContextGo inline sidecar.',
    implementationOwner: 'connector-repo',
    externalCatalogConnector: 'gmail',
    supportSources: CONNECTOR_SUPPORT_SOURCES.gmail,
  },
  {
    id: 'google-keep',
    name: 'Google Keep',
    websiteUrl: 'https://keep.google.com',
    domain: 'keep.google.com',
    category: 'googleWorkspace',
    resources: ['docs'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'google-workspace-admin-export',
    name: 'Google Workspace Admin Export',
    websiteUrl: 'https://workspace.google.com',
    domain: 'workspace.google.com',
    category: 'googleWorkspace',
    resources: ['files', 'docs', 'analytics'],
    authType: 'serviceAccount',
    stage: 'planned',
  },
  {
    id: 'google-chat',
    name: 'Google Chat',
    websiteUrl: 'https://chat.google.com',
    domain: 'chat.google.com',
    category: 'googleWorkspace',
    resources: ['chat'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'google-meet',
    name: 'Google Meet',
    websiteUrl: 'https://meet.google.com',
    domain: 'meet.google.com',
    category: 'googleWorkspace',
    resources: ['calendar', 'chat'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'lark',
    name: 'Feishu / Lark',
    websiteUrl: 'https://open.feishu.cn',
    domain: 'open.feishu.cn',
    category: 'collaboration',
    resources: ['chat', 'docs', 'calendar', 'files'],
    authType: 'oauth',
    stage: 'priority',
    summary:
      'The Feishu connector runtime lives in the standalone connector project, which wraps the official lark-cli and keeps runtime/auth state outside the ContextGo app.',
    implementationOwner: 'connector-repo',
    externalCatalogConnector: 'feishu',
    supportSources: CONNECTOR_SUPPORT_SOURCES.lark,
  },
  {
    id: 'dingtalk-bot',
    name: 'DingTalk Bot',
    websiteUrl: 'https://open.dingtalk.com',
    domain: 'open.dingtalk.com',
    category: 'collaboration',
    resources: ['chat', 'docs', 'tasks'],
    authType: 'bot',
    stage: 'priority',
  },
  {
    id: 'wechat',
    name: 'WeChat',
    websiteUrl: 'https://weixin.qq.com',
    domain: 'weixin.qq.com',
    category: 'collaboration',
    resources: ['chat', 'webPages'],
    authType: 'none',
    stage: 'priority',
  },
  {
    id: 'slack',
    name: 'Slack',
    websiteUrl: 'https://slack.com',
    domain: 'slack.com',
    category: 'collaboration',
    resources: ['chat', 'files', 'docs'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'microsoft-teams',
    name: 'Microsoft Teams',
    websiteUrl: 'https://www.microsoft.com/microsoft-teams',
    domain: 'microsoft.com',
    category: 'collaboration',
    resources: ['chat', 'files', 'calendar'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'discord',
    name: 'Discord',
    websiteUrl: 'https://discord.com',
    domain: 'discord.com',
    category: 'collaboration',
    resources: ['chat'],
    authType: 'bot',
    stage: 'planned',
  },
  {
    id: 'telegram',
    name: 'Telegram',
    websiteUrl: 'https://telegram.org',
    domain: 'telegram.org',
    category: 'collaboration',
    resources: ['chat'],
    authType: 'bot',
    stage: 'planned',
  },
  {
    id: 'wecom',
    name: 'WeCom',
    websiteUrl: 'https://work.weixin.qq.com',
    domain: 'work.weixin.qq.com',
    category: 'collaboration',
    resources: ['chat', 'files', 'calendar'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'zoom',
    name: 'Zoom',
    websiteUrl: 'https://zoom.us',
    domain: 'zoom.us',
    category: 'collaboration',
    resources: ['calendar', 'chat'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'github',
    name: 'GitHub',
    websiteUrl: 'https://github.com',
    domain: 'github.com',
    category: 'development',
    resources: ['repositories', 'issues', 'docs'],
    authType: 'pat',
    stage: 'priority',
    summary:
      'The GitHub connector runtime lives in the standalone connector project, which wraps the official gh CLI and exposes source and workflow readiness back to ContextGo.',
    implementationOwner: 'connector-repo',
    externalCatalogConnector: 'github',
    supportSources: [
      {
        kind: 'official-docs',
        label: 'GitHub CLI Manual',
        url: 'https://cli.github.com/manual/',
        description: 'Official gh CLI reference for auth, api passthrough, and repository-oriented command workflows.',
      },
      {
        kind: 'official-runtime',
        label: 'gh CLI',
        url: 'https://github.com/cli/cli',
        description: 'Official GitHub CLI used by the connector project for auth state and API passthrough.',
      },
      {
        kind: 'connector-repo',
        label: 'Connector Repository',
        url: 'https://github.com/contextgo/connector',
        description:
          'The standalone connector project owns the GitHub runtime wrapper, source registry, and collect/store readiness model.',
      },
    ],
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    websiteUrl: 'https://gitlab.com',
    domain: 'gitlab.com',
    category: 'development',
    resources: ['repositories', 'issues', 'docs'],
    authType: 'pat',
    stage: 'planned',
  },
  {
    id: 'jira',
    name: 'Jira',
    websiteUrl: 'https://www.atlassian.com/software/jira',
    domain: 'atlassian.com',
    category: 'development',
    resources: ['issues', 'tasks'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'linear',
    name: 'Linear',
    websiteUrl: 'https://linear.app',
    domain: 'linear.app',
    category: 'development',
    resources: ['issues', 'tasks'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'sentry',
    name: 'Sentry',
    websiteUrl: 'https://sentry.io',
    domain: 'sentry.io',
    category: 'development',
    resources: ['incidents', 'analytics'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    websiteUrl: 'https://vercel.com',
    domain: 'vercel.com',
    category: 'development',
    resources: ['analytics', 'incidents'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'netlify',
    name: 'Netlify',
    websiteUrl: 'https://www.netlify.com',
    domain: 'netlify.com',
    category: 'development',
    resources: ['analytics', 'incidents'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'arxiv',
    name: 'arXiv',
    websiteUrl: 'https://arxiv.org',
    domain: 'arxiv.org',
    category: 'knowledge',
    resources: ['docs', 'webPages'],
    authType: 'none',
    stage: 'priority',
  },
  {
    id: 'reddit',
    name: 'Reddit',
    websiteUrl: 'https://www.reddit.com',
    domain: 'reddit.com',
    category: 'knowledge',
    resources: ['webPages', 'chat'],
    authType: 'none',
    stage: 'priority',
  },
  {
    id: 'rss',
    name: 'RSS / Atom',
    websiteUrl: 'https://www.rssboard.org',
    domain: 'rssboard.org',
    category: 'knowledge',
    resources: ['webPages', 'docs'],
    authType: 'none',
    stage: 'priority',
  },
  {
    id: 'x',
    name: 'X',
    websiteUrl: 'https://x.com',
    domain: 'x.com',
    category: 'knowledge',
    resources: ['webPages', 'chat'],
    authType: 'none',
    stage: 'priority',
  },
  {
    id: 'xiaohongshu',
    name: 'Xiaohongshu',
    websiteUrl: 'https://www.xiaohongshu.com',
    domain: 'xiaohongshu.com',
    category: 'knowledge',
    resources: ['webPages', 'analytics'],
    authType: 'none',
    stage: 'priority',
    externalCatalogConnector: 'xiaohongshu',
  },
  {
    id: 'douyin',
    name: 'Douyin',
    websiteUrl: 'https://www.douyin.com',
    domain: 'douyin.com',
    category: 'knowledge',
    resources: ['webPages', 'analytics'],
    authType: 'none',
    stage: 'priority',
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    websiteUrl: 'https://www.tiktok.com',
    domain: 'tiktok.com',
    category: 'knowledge',
    resources: ['webPages', 'analytics'],
    authType: 'none',
    stage: 'priority',
  },
  {
    id: 'youtube',
    name: 'YouTube',
    websiteUrl: 'https://www.youtube.com',
    domain: 'youtube.com',
    category: 'knowledge',
    resources: ['webPages', 'analytics'],
    authType: 'none',
    stage: 'priority',
  },
  {
    id: 'notion',
    name: 'Notion',
    websiteUrl: 'https://www.notion.so',
    domain: 'notion.so',
    category: 'knowledge',
    resources: ['docs', 'wiki'],
    authType: 'oauth',
    stage: 'priority',
  },
  {
    id: 'confluence',
    name: 'Confluence',
    websiteUrl: 'https://www.atlassian.com/software/confluence',
    domain: 'atlassian.com',
    category: 'knowledge',
    resources: ['wiki', 'docs'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'coda',
    name: 'Coda',
    websiteUrl: 'https://coda.io',
    domain: 'coda.io',
    category: 'knowledge',
    resources: ['docs', 'tasks'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    websiteUrl: 'https://obsidian.md',
    domain: 'obsidian.md',
    category: 'knowledge',
    resources: ['docs', 'wiki'],
    authType: 'apiKey',
    stage: 'planned',
    externalCatalogConnector: 'obsidian',
  },
  {
    id: 'slite',
    name: 'Slite',
    websiteUrl: 'https://slite.com',
    domain: 'slite.com',
    category: 'knowledge',
    resources: ['docs', 'wiki'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'onenote-export',
    name: 'OneNote Export',
    websiteUrl: 'https://www.onenote.com',
    domain: 'onenote.com',
    category: 'knowledge',
    resources: ['docs', 'files'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'apple-notes-export',
    name: 'Apple Notes Export',
    websiteUrl: 'https://www.icloud.com/notes',
    domain: 'icloud.com',
    category: 'knowledge',
    resources: ['docs', 'files'],
    authType: 'native',
    stage: 'planned',
  },
  {
    id: 'craft-export',
    name: 'Craft Export',
    websiteUrl: 'https://www.craft.do',
    domain: 'craft.do',
    category: 'knowledge',
    resources: ['docs', 'files'],
    authType: 'native',
    stage: 'planned',
  },
  {
    id: 'bear-export',
    name: 'Bear Export',
    websiteUrl: 'https://bear.app',
    domain: 'bear.app',
    category: 'knowledge',
    resources: ['docs', 'files'],
    authType: 'native',
    stage: 'planned',
  },
  {
    id: 'evernote',
    name: 'Evernote',
    websiteUrl: 'https://evernote.com',
    domain: 'evernote.com',
    category: 'knowledge',
    resources: ['docs', 'wiki'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'apple-journal-export',
    name: 'Apple Journal Export',
    websiteUrl: 'https://www.apple.com/ios/journal/',
    domain: 'apple.com',
    category: 'knowledge',
    resources: ['docs', 'files'],
    authType: 'native',
    stage: 'planned',
  },
  {
    id: 'roam',
    name: 'Roam Research',
    websiteUrl: 'https://roamresearch.com',
    domain: 'roamresearch.com',
    category: 'knowledge',
    resources: ['docs', 'wiki'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'hacker-news',
    name: 'Hacker News',
    websiteUrl: 'https://news.ycombinator.com',
    domain: 'ycombinator.com',
    category: 'knowledge',
    resources: ['webPages', 'chat'],
    authType: 'none',
    stage: 'planned',
  },
  {
    id: 'figma',
    name: 'Figma',
    websiteUrl: 'https://www.figma.com',
    domain: 'figma.com',
    category: 'design',
    resources: ['designs', 'docs'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'miro',
    name: 'Miro',
    websiteUrl: 'https://miro.com',
    domain: 'miro.com',
    category: 'design',
    resources: ['designs', 'docs'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'dropbox',
    name: 'Dropbox',
    websiteUrl: 'https://www.dropbox.com',
    domain: 'dropbox.com',
    category: 'storage',
    resources: ['files'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'onedrive',
    name: 'OneDrive',
    websiteUrl: 'https://onedrive.live.com',
    domain: 'onedrive.live.com',
    category: 'storage',
    resources: ['files'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'box',
    name: 'Box',
    websiteUrl: 'https://www.box.com',
    domain: 'box.com',
    category: 'storage',
    resources: ['files'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'tianyancha',
    name: 'Tianyancha',
    websiteUrl: 'https://www.tianyancha.com',
    domain: 'tianyancha.com',
    category: 'business',
    resources: ['webPages', 'analytics'],
    authType: 'none',
    stage: 'priority',
  },
  {
    id: 'company-cn',
    name: 'Company CN',
    websiteUrl: 'https://contextgo.io',
    domain: 'contextgo.io',
    category: 'business',
    resources: ['webPages', 'analytics'],
    authType: 'apiKey',
    stage: 'planned',
  },
  {
    id: 'media-cn',
    name: 'Media CN',
    websiteUrl: 'https://contextgo.io',
    domain: 'contextgo.io',
    category: 'business',
    resources: ['webPages', 'analytics'],
    authType: 'apiKey',
    stage: 'planned',
  },
  {
    id: 'corp-intel-global',
    name: 'Global Corp Intel',
    websiteUrl: 'https://contextgo.io',
    domain: 'contextgo.io',
    category: 'business',
    resources: ['webPages', 'analytics'],
    authType: 'apiKey',
    stage: 'planned',
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    websiteUrl: 'https://www.linkedin.com',
    domain: 'linkedin.com',
    category: 'business',
    resources: ['webPages', 'analytics'],
    authType: 'none',
    stage: 'planned',
  },
  {
    id: 'product-hunt',
    name: 'Product Hunt',
    websiteUrl: 'https://www.producthunt.com',
    domain: 'producthunt.com',
    category: 'business',
    resources: ['webPages', 'analytics'],
    authType: 'none',
    stage: 'planned',
  },
  {
    id: 'jobs',
    name: 'Jobs',
    websiteUrl: 'https://contextgo.io',
    domain: 'contextgo.io',
    category: 'business',
    resources: ['webPages', 'analytics'],
    authType: 'apiKey',
    stage: 'planned',
  },
  {
    id: 'investment-database',
    name: 'Investment Database',
    websiteUrl: 'https://contextgo.io',
    domain: 'contextgo.io',
    category: 'business',
    resources: ['databases', 'analytics'],
    authType: 'apiKey',
    stage: 'planned',
  },
  {
    id: 'salesforce',
    name: 'Salesforce',
    websiteUrl: 'https://www.salesforce.com',
    domain: 'salesforce.com',
    category: 'business',
    resources: ['crm'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    websiteUrl: 'https://www.hubspot.com',
    domain: 'hubspot.com',
    category: 'business',
    resources: ['crm', 'email'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'zendesk',
    name: 'Zendesk',
    websiteUrl: 'https://www.zendesk.com',
    domain: 'zendesk.com',
    category: 'business',
    resources: ['tasks', 'chat'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'intercom',
    name: 'Intercom',
    websiteUrl: 'https://www.intercom.com',
    domain: 'intercom.com',
    category: 'business',
    resources: ['chat', 'crm'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'shopify',
    name: 'Shopify',
    websiteUrl: 'https://www.shopify.com',
    domain: 'shopify.com',
    category: 'business',
    resources: ['commerce', 'analytics'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    websiteUrl: 'https://stripe.com',
    domain: 'stripe.com',
    category: 'business',
    resources: ['commerce', 'analytics'],
    authType: 'apiKey',
    stage: 'planned',
  },
  {
    id: 'volcengine-aisearch',
    name: 'Volcengine AI Search',
    websiteUrl: 'https://www.volcengine.com',
    domain: 'volcengine.com',
    category: 'data',
    resources: ['webPages', 'analytics'],
    authType: 'apiKey',
    stage: 'planned',
  },
  {
    id: 'microsoft-365-graph',
    name: 'Microsoft 365 Graph',
    websiteUrl: 'https://developer.microsoft.com/en-us/graph',
    domain: 'microsoft.com',
    category: 'data',
    resources: ['files', 'email', 'calendar'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'm365-cli-shell',
    name: 'M365 CLI Shell',
    websiteUrl: 'https://pnp.github.io/cli-microsoft365/',
    domain: 'pnp.github.io',
    category: 'data',
    resources: ['files', 'docs', 'email'],
    authType: 'native',
    stage: 'planned',
  },
  {
    id: 'airtable',
    name: 'Airtable',
    websiteUrl: 'https://www.airtable.com',
    domain: 'airtable.com',
    category: 'data',
    resources: ['databases', 'docs'],
    authType: 'oauth',
    stage: 'planned',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    websiteUrl: 'https://supabase.com',
    domain: 'supabase.com',
    category: 'data',
    resources: ['databases'],
    authType: 'serviceAccount',
    stage: 'planned',
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    websiteUrl: 'https://www.postgresql.org',
    domain: 'postgresql.org',
    category: 'data',
    resources: ['databases'],
    authType: 'serviceAccount',
    stage: 'planned',
  },
  {
    id: 'bigquery',
    name: 'BigQuery',
    websiteUrl: 'https://cloud.google.com/bigquery',
    domain: 'cloud.google.com',
    category: 'data',
    resources: ['analytics', 'databases'],
    authType: 'serviceAccount',
    stage: 'planned',
  },
  {
    id: 'snowflake',
    name: 'Snowflake',
    websiteUrl: 'https://www.snowflake.com',
    domain: 'snowflake.com',
    category: 'data',
    resources: ['analytics', 'databases'],
    authType: 'oauth',
    stage: 'planned',
  },
];

const SUPPORTED_CONNECTOR_IDS = new Set([
  'contextgo-clipboard',
  'contextgo-browser-extension',
  'google-drive',
  'google-docs',
  'google-sheets',
  'gmail',
  'google-calendar',
  'lark',
  'github',
  'obsidian',
  'notion',
  'arxiv',
  'reddit',
  'rss',
  'x',
  'xiaohongshu',
  'douyin',
  'tiktok',
  'youtube',
  'wechat',
  'tianyancha',
]);

export const CONNECTORS: ConnectorDefinition[] = RAW_CONNECTORS.map((connector) => ({
  ...connector,
  supportStatus:
    connector.supportStatus ?? (SUPPORTED_CONNECTOR_IDS.has(connector.id) ? 'supported' : 'notSupportedYet'),
  localLogo: CONNECTOR_LOCAL_LOGOS[connector.id] || connector.localLogo,
}));

export const CONNECTOR_MAP = new Map(CONNECTORS.map((connector) => [connector.id, connector]));
