import SwiftUI

struct ContentView: View {
  @EnvironmentObject private var connectionStore: ConnectionStore
  @StateObject private var webViewStore = WebViewStore()

  var body: some View {
    NavigationStack {
      Group {
        if let targetURL = connectionStore.targetURL {
          ShellBrowserView(targetURL: targetURL)
            .environmentObject(connectionStore)
            .environmentObject(webViewStore)
        } else {
          ConnectionView()
            .environmentObject(connectionStore)
        }
      }
      .navigationTitle("AionUi Shell")
      .navigationBarTitleDisplayMode(.inline)
    }
  }
}

private struct ConnectionView: View {
  @EnvironmentObject private var connectionStore: ConnectionStore

  var body: some View {
    ScrollView {
      VStack(alignment: .leading, spacing: 20) {
        Text("Connect To Your AionUi Host")
          .font(.title2)
          .fontWeight(.semibold)

        Text("Paste a WebUI base URL like http://192.168.1.10:3000 or a /qr-login?token=... link generated by AionUi.")
          .foregroundStyle(.secondary)

        TextField("http://192.168.1.10:3000", text: $connectionStore.inputText)
          .textInputAutocapitalization(.never)
          .autocorrectionDisabled()
          .keyboardType(.URL)
          .textFieldStyle(.roundedBorder)

        Button(action: {
          _ = connectionStore.connect()
        }) {
          Text("Connect")
            .frame(maxWidth: .infinity)
        }
        .buttonStyle(.borderedProminent)

        if let validationMessage = connectionStore.validationMessage {
          Text(validationMessage)
            .font(.footnote)
            .foregroundStyle(.red)
        }

        VStack(alignment: .leading, spacing: 8) {
          Text("How it works")
            .font(.headline)

          Text("1. Start AionUi with WebUI or standalone server mode on a reachable machine.")
          Text("2. Enter the host address, or paste the QR-login URL from AionUi.")
          Text("3. The shell stores the last successful endpoint and reopens it next time.")
        }
        .font(.footnote)
        .foregroundStyle(.secondary)
      }
      .padding(24)
    }
    .background(Color(.systemGroupedBackground))
  }
}

private struct ShellBrowserView: View {
  @EnvironmentObject private var connectionStore: ConnectionStore
  @EnvironmentObject private var webViewStore: WebViewStore

  let targetURL: URL

  var body: some View {
    VStack(spacing: 0) {
      HStack(spacing: 12) {
        Button("Back") {
          webViewStore.goBack()
        }
        .buttonStyle(.bordered)

        Button("Reload") {
          webViewStore.reload()
        }
        .buttonStyle(.bordered)

        Spacer(minLength: 12)

        Button("Reconnect") {
          connectionStore.reset()
        }
        .buttonStyle(.borderedProminent)
      }
      .padding(.horizontal, 16)
      .padding(.vertical, 12)
      .background(.thinMaterial)

      Divider()

      ShellWebView(store: webViewStore, url: targetURL)
        .ignoresSafeArea(edges: .bottom)
    }
  }
}
